services:
  server:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://admin:admin1234@issgeo_db:5432/issgeo_db
      JWT_SECRET: your_jwt_secret_key
      ADMIN_PASSWORD: Password123.
      NODE_ENV: production
    depends_on:
      issgeo_db:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.issgeo.rule=Host(`issgeo.com`) || Host(`www.issgeo.com`)"
      - "traefik.http.routers.issgeo.entrypoints=https"
      - "traefik.http.routers.issgeo.tls=true"
      - "traefik.http.routers.issgeo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.issgeo.tls.domains[0].main=issgeo.com"
      - "traefik.http.routers.issgeo.tls.domains[0].sans=www.issgeo.com"
      - "traefik.http.services.issgeo.loadbalancer.server.port=3000"
      - "traefik.http.routers.issgeo-http.rule=Host(`issgeo.com`) || Host(`www.issgeo.com`)"
      - "traefik.http.routers.issgeo-http.entrypoints=http"
      - "traefik.http.routers.issgeo-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  issgeo_db:
    image: postgres:17
    #container_name: issgeo_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: issgeo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "issgeo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

# services:
#   server:
#     build:
#       context: .
#     environment:
#       DATABASE_URL: postgres://admin:admin1234@issgeo_db:5432/issgeo_db
#       JWT_SECRET: your_jwt_secret_key
#       ADMIN_PASSWORD: Password123.
#       NODE_ENV: production
#     # ports:
#     #   - 3000:3000
#      depends_on:
#       issgeo_db:
#         condition: service_healthy  # ← attend que la DB soit prête

#   issgeo_db:
#     image: postgres:17
#     container_name: issgeo_db
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: admin1234
#       POSTGRES_DB: issgeo_db
#     ports:
#       - "5455:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD", "pg_isready", "-U", "doni", "-d", "doni_db"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     restart: unless-stopped

# volumes:
#   postgres_data:

